base=float(input("dijite el valor de la base"))
altura=float(input("dijite el valor de la altura"))
hipotenusa=float(input("dijite el valor de la hipotenusa"))
area=(base+altura+hipotenusa)
print ("el perimetro del triangulo rectangulo es", area)